model:
  class: LGBModel
  kwargs:
    colsample_bytree: 0.8879
    early_stopping_rounds: 100
    lambda_l1: 205.6999
    lambda_l2: 580.9768
    learning_rate: 0.0421
    loss: mse
    max_depth: 8
    num_boost_round: 1000
    num_leaves: 210
    num_threads: 20
    subsample: 0.8789
  module_path: qlib.contrib.model.gbdt
